### ISSUE TITLE
What are plans for this repo?  

### ISSUE THREAD

**Issue by StephenGriffies** [mom-ocean/MOM5-examples#1]
Looks like this repo has been idle since November 2017.  What are the plans?  Its description is confusing since users might think there are no example test cases for MOM5, whereas there are many under the MOM5 repo.

**Comment by navidcy** [comment]
Let's delete the repo? I got actually confused by it.

However, me and @dhruvbhagtani were looking for the examples in the MOM5 repo and couldn't locate them. We could only find pdf files describing the examples but nowhere the actual source files of the examples are to be found. Are we missing anything? We were hoping to see some ocean-only examples somewhere...

**Comment by aidanheerdegen** [comment]
Related issue

https://github.com/COSIMA/access-om2/issues/42

**Comment by aidanheerdegen** [comment]
See also

https://github.com/mom-ocean/MOM5/issues/197

**Comment by aidanheerdegen** [comment]
There is an issue with some of the test cases having large binary inputs, but at least the configuration files could be stored here.

Smaller cases can be stored in their entirety. For example I have added the `bowl1` case 

https://github.com/mom-ocean/MOM5-examples/pull/2

I intend to use this in the MOM5 CI testing, so it made sense to add it here.

**Comment by aidanheerdegen** [comment]
I have kept the `bowl1` branch, as it occurred to me could use this as a strategy to keep all configs in a single repo, but be able to check out individual configurations. If all updates to a config are pushed to the branch with that config name, and then merged, then it should be possible to check out *only* that branch to select a single configuration.

**Comment by aidanheerdegen** [comment]
I've added six of the smaller examples in total. I'll close this issue, and if there is demand for some of the larger examples we can look into solutions for large binaries, e.g. [git annex](https://git-annex.branchable.com) or [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)
